### ISSUE TITLE
:sparkle: Start timing how long boots and bars have been on when someone clicks start tracking

### ISSUE THREAD

**Issue by jakeshepherd** [jakeshepherd/Club-Foot-App#10]
This will be the front end and back end for starting and ending the boots and bars time tracking.
Do with TDD:
- [ ] Send start time to database
- [ ] Send end time to database
- [ ] Save Duration into database per user

One user can have as many start and end times in a day
